services:
  ngrok:
    image: ngrok/ngrok:3-alpine
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
      - NGROK_CONFIG=/home/ngrok/.config/ngrok/ngrok.yml
    network_mode: host
    volumes:
      - ./data/ngrok/ngrok.yml:/home/ngrok/.config/ngrok/ngrok.yml

  vkbot:
    build: .
    container_name: vkbot
    network_mode: host
    environment:
      - TZ=Europe/Moscow
      - VK_CALLBACK_AUTH_TOKEN=${VK_ACCESS_TOKEN}
      - VK_CALLBACK_API_VERSION=${VK_API_VERSION}
      - VK_CONFIRMATION_CODE=${VK_CONFIRMATION_CODE}
    restart: always
